"""
Project-local pygame recipe for Tarkov2D (based on p4a's official recipe).

Why this file exists
--------------------
p4a's stock recipe produces a pygame that cannot be loaded on arm64.  Android's
linker resolves *every* relocation when it dlopen()s a library, so one symbol
that no library in the APK defines makes the whole module unloadable:

    ImportError: dlopen failed: cannot locate symbol
    "<name>" referenced by ".../pygame/surface.so"

pygame/__init__.py imports pygame.surface while starting up, so the game died
before it could open a window: the Tarkov2D 1.0.8 crash-on-launch.

Three undefined symbols had to be handled, each visible only after the previous
one was fixed:

  1. alphablit_alpha_sse2_argb_surf_alpha
     Defined in src_c/simd_blitters_sse2.c, which
     buildconfig/Setup.Android.SDL2.in forgets to compile.  On aarch64 that
     file uses include/sse2neon.h (SSE2 -> NEON), so it builds fine for arm64.

  2. pg_has_avx2
     Defined only by src_c/simd_blitters_avx2.c, which is never compiled for
     aarch64.  pygame's setup.py also turns on -mavx2 whenever
     platform.machine() reports x86/amd64 - which is what the CI *runner*
     reports even though we cross-compile for arm64.

  3. pg_avx2_at_runtime_but_uncompiled        <-- 1.0.8 shipped with this one
     Same file, same reason.  Its only caller in surface.so is
     pg_warn_simd_at_runtime_but_uncompiled(), i.e. it decides whether to print
     "your CPU has AVX2 but this build has no AVX2 code".  On arm64 the answer
     must be 0.

Fix strategy
------------
(a) Link src_c/simd_blitters_sse2.c into surface.so.
(b) Link a generated translation unit that provides WEAK definitions for the
    whole AVX2 family.  Weak definitions lose against any real definition, so
    this can never conflict with a proper build, and it is what actually
    guarantees a loadable surface.so: even if the AVX2 code grows a new entry
    point upstream, the reference resolves instead of shipping a module that
    crashes the app on launch.
(c) Verify after the APK is built - see tools/check_android_symbols.py, which
    the workflow runs.  A build must never again produce a pygame module with
    an unresolved internal symbol.

Deliberately NOT done: rewriting src_c/simd_blitters.h.  The previous version
of this recipe stripped the AVX2 declarations with regexes, which is fragile
and cannot stub a name that the pattern does not match - exactly how symbol (3)
was missed.  Weak definitions cover every name without touching the header.

Keep this file pure ASCII: the project has been bitten by GBK-encoded build
files before.
"""
import os
from os.path import exists, join

from pythonforandroid.recipe import CompiledComponentsPythonRecipe
from pythonforandroid.toolchain import current_directory

# The line in buildconfig/Setup.Android.SDL2.in that builds surface.so.
SURFACE_LINE = "surface src_c/surface.c src_c/alphablit.c src_c/surface_fill.c"

# Extra translation units that must be linked into surface.so.
SSE2_BLITTERS = "src_c/simd_blitters_sse2.c"
AVX2_STUBS = "src_c/tarkov2d_avx2_stubs.c"

# AVX2 blitters: declared in src_c/simd_blitters.h, defined only by
# src_c/simd_blitters_avx2.c (never compiled for aarch64).
AVX2_BLIT_SYMBOLS = [
    "blit_blend_rgba_mul_avx2", "blit_blend_rgb_mul_avx2",
    "blit_blend_rgba_add_avx2", "blit_blend_rgb_add_avx2",
    "blit_blend_rgba_sub_avx2", "blit_blend_rgb_sub_avx2",
    "blit_blend_rgba_max_avx2", "blit_blend_rgb_max_avx2",
    "blit_blend_rgba_min_avx2", "blit_blend_rgb_min_avx2",
]

# The no-argument AVX2 helpers.  pg_avx2_at_runtime_but_uncompiled is the one
# that shipped undefined in 1.0.8 - never remove it from this list.
AVX2_NOARG_SYMBOLS = [
    "pg_has_avx2",
    "pg_avx2_at_runtime_but_uncompiled",
]

ALL_AVX2_SYMBOLS = AVX2_NOARG_SYMBOLS + AVX2_BLIT_SYMBOLS

# Written into the pygame source tree and added to surface.so's link unit.
# No #include on purpose: this file must never pull in simd_blitters.h, so it
# cannot collide with whatever that header declares.
STUB_SOURCE = """/* Generated by Tarkov2D's p4a-recipes/pygame/__init__.py - do not edit.
 *
 * aarch64 has no AVX2, so pygame's src_c/simd_blitters_avx2.c is never
 * compiled, yet src_c/simd_blitters.h declares the AVX2 entry points outside
 * any preprocessor guard.  Any surviving reference to them leaves surface.so
 * with an undefined symbol, and Android's linker refuses to dlopen() such a
 * library - pygame then fails to import and the game dies at launch.
 *
 * These WEAK definitions keep pygame importable:
 *   pg_has_avx2() == 0                       -> AVX2 blit path is dead code
 *   pg_avx2_at_runtime_but_uncompiled() == 0 -> no "AVX2 missing" warning
 * A weak symbol always loses against a real definition, so this file cannot
 * break a build that defines them properly.
 */
struct SDL_BlitInfo;

__attribute__((weak)) int
pg_has_avx2(void)
{
    return 0;
}

__attribute__((weak)) int
pg_avx2_at_runtime_but_uncompiled(void)
{
    return 0;
}

%s
"""


class Pygame2Recipe(CompiledComponentsPythonRecipe):
    version = '2.5.2'
    url = 'https://github.com/pygame/pygame/archive/{version}.tar.gz'

    site_packages_name = 'pygame'
    name = 'pygame'

    depends = ['sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'setuptools', 'jpeg', 'png']
    call_hostpython_via_targetpython = False  # Due to setuptools
    install_in_hostpython = False

    # ------------------------------------------------------------------ build
    def prebuild_arch(self, arch):
        super().prebuild_arch(arch)
        with current_directory(self.get_build_dir(arch.arch)):
            self._write_avx2_stubs()
            setup_template = open(join("buildconfig", "Setup.Android.SDL2.in")).read()
            setup_template = self._patch_surface_line(setup_template)
            env = self.get_recipe_env(arch)
            env['ANDROID_ROOT'] = join(self.ctx.ndk.sysroot, 'usr')

            png = self.get_recipe('png', self.ctx)
            png_lib_dir = join(png.get_build_dir(arch.arch), '.libs')
            png_inc_dir = png.get_build_dir(arch)

            jpeg = self.get_recipe('jpeg', self.ctx)
            jpeg_inc_dir = jpeg_lib_dir = jpeg.get_build_dir(arch.arch)

            sdl_mixer_includes = ""
            sdl2_mixer_recipe = self.get_recipe('sdl2_mixer', self.ctx)
            for include_dir in sdl2_mixer_recipe.get_include_dirs(arch):
                sdl_mixer_includes += f"-I{include_dir} "

            sdl2_image_includes = ""
            sdl2_image_recipe = self.get_recipe('sdl2_image', self.ctx)
            for include_dir in sdl2_image_recipe.get_include_dirs(arch):
                sdl2_image_includes += f"-I{include_dir} "

            setup_file = setup_template.format(
                sdl_includes=(
                    " -I" + join(self.ctx.bootstrap.build_dir, 'jni', 'SDL', 'include') +
                    " -L" + join(self.ctx.bootstrap.build_dir, "libs", str(arch)) +
                    " -L" + png_lib_dir + " -L" + jpeg_lib_dir + " -L" + arch.ndk_lib_dir_versioned),
                sdl_ttf_includes="-I"+join(self.ctx.bootstrap.build_dir, 'jni', 'SDL2_ttf'),
                sdl_image_includes=sdl2_image_includes,
                sdl_mixer_includes=sdl_mixer_includes,
                jpeg_includes="-I"+jpeg_inc_dir,
                png_includes="-I"+png_inc_dir,
                freetype_includes=""
            )
            open("Setup", "w").write(setup_file)
            self._check_setup()

    # ------------------------------------------------ new sources for the .so
    def _write_avx2_stubs(self):
        """Create the weak-definition source file next to pygame's sources."""
        blits = "\n".join(
            "__attribute__((weak)) void\n%s(struct SDL_BlitInfo *info)\n{\n"
            "    (void)info;\n}\n" % name
            for name in AVX2_BLIT_SYMBOLS
        )
        path = AVX2_STUBS
        if exists(path):
            os.remove(path)
        with open(path, "w") as f:
            f.write(STUB_SOURCE % blits)
        print("[pygame-recipe] wrote %s with %d weak AVX2 stub(s)" % (path, len(ALL_AVX2_SYMBOLS)))

    def _patch_surface_line(self, setup_template):
        """
        Make surface.so link simd_blitters_sse2.c and the weak AVX2 stubs.

        Both extra objects MUST end up in the same extension module as
        alphablit.c - the undefined references come from alphablit.o, so a
        separate module would not fix anything.  If the template ever changes
        shape we fail the build loudly instead of shipping another APK that
        crashes on the phone.
        """
        extras = [SSE2_BLITTERS, AVX2_STUBS]
        for line in setup_template.splitlines():
            if line.strip().startswith(SURFACE_LINE):
                # Same-line append on purpose: this is the exact shape that
                # produced the working 1.0.8 surface.so for
                # src_c/simd_blitters_sse2.c, so the Setup parser is known to
                # accept it.
                todo = [e for e in extras if e not in setup_template]
                if not todo:
                    print("[pygame-recipe] Setup already lists %s" % ", ".join(extras))
                    return setup_template
                patched = SURFACE_LINE + " " + " ".join(todo)
                setup_template = setup_template.replace(SURFACE_LINE, patched)
                print("[pygame-recipe] Setup: surface.so now also builds %s"
                      % ", ".join(todo))
                return setup_template
        raise RuntimeError(
            "pygame-recipe: %r not found in buildconfig/Setup.Android.SDL2.in. "
            "src_c/simd_blitters_sse2.c and %s must be compiled into surface.so "
            "or the APK will crash on launch with "
            "'cannot locate symbol'. Update SURFACE_LINE in "
            "p4a-recipes/pygame/__init__.py." % (SURFACE_LINE, AVX2_STUBS)
        )

    def _check_setup(self):
        if not exists("Setup"):
            raise RuntimeError("pygame-recipe: the Setup file was not generated")
        text = open("Setup").read()
        missing = [e for e in (SSE2_BLITTERS, AVX2_STUBS) if e not in text]
        if missing:
            raise RuntimeError("pygame-recipe: Setup is missing %s - surface.so "
                               "would be unloadable on the phone" % ", ".join(missing))

    # -------------------------------------------------------------- toolchain
    def get_recipe_env(self, arch):
        env = super().get_recipe_env(arch)
        env['USE_SDL2'] = '1'
        env["PYGAME_CROSS_COMPILE"] = "TRUE"
        env["PYGAME_ANDROID"] = "TRUE"

        # Force pygame's AVX2 detection off.  pygame's setup.py does:
        #     if os.environ.get('PYGAME_DETECT_AVX2', '') != '':
        #         avx2_filenames = ['simd_blitters_avx2']
        #         ... and then enables -mavx2 whenever platform.machine() is
        #         x86/amd64 -- exactly what the CI runner reports even though we
        #         cross-compile for arm64.  That is how surface.so ended up
        #         referencing pg_has_avx2 and pg_avx2_at_runtime_but_uncompiled.
        for key in ("PYGAME_DETECT_AVX2", "MAC_ARCH"):
            env.pop(key, None)
        os.environ.pop("PYGAME_DETECT_AVX2", None)

        # Keep the SIMD blitters from being inlined away (sse2neon.h marks its
        # helpers FORCE_INLINE) and make sure the ARM NEON path is on.
        cflags = env.get("CFLAGS", "")
        for flag in ("-fno-inline-functions", "-DPG_ENABLE_ARM_NEON"):
            if flag not in cflags:
                cflags += " " + flag
        env["CFLAGS"] = cflags
        return env


recipe = Pygame2Recipe()
